
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface AIProfile {
  id: string;
  summary: string;
  resume_id?: string;
  parent_id?: string;
  created_at: string;
}

export const useAIProfiles = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [profiles, setProfiles] = useState<AIProfile[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();

  const generateAIProfile = async (resumeId: string, notes: string[]) => {
    if (!user) return;

    setIsGenerating(true);
    try {
      // Call edge function to generate AI profile
      const { data, error } = await supabase.functions.invoke('generate-ai-profile', {
        body: {
          resumeId,
          notes,
          userId: user.id
        }
      });

      if (error) throw error;

      const newProfile: AIProfile = {
        id: data.id,
        summary: data.summary,
        resume_id: resumeId,
        parent_id: user.id,
        created_at: data.created_at
      };

      setProfiles(prev => [newProfile, ...prev]);
      
      toast({
        title: "Success!",
        description: "AI profile generated successfully"
      });

      return newProfile;
    } catch (error) {
      console.error('Failed to generate AI profile:', error);
      toast({
        title: "Error",
        description: "Failed to generate AI profile",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const loadAIProfiles = async () => {
    if (!user) return;

    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('ai_profiles')
        .select('*')
        .eq('parent_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;

      const formattedProfiles: AIProfile[] = (data || []).map(profile => ({
        id: profile.id,
        summary: profile.summary,
        resume_id: profile.resume_id,
        parent_id: profile.parent_id,
        created_at: profile.created_at
      }));

      setProfiles(formattedProfiles);
    } catch (error) {
      console.error('Failed to load AI profiles:', error);
      toast({
        title: "Error",
        description: "Failed to load AI profiles",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const deleteAIProfile = async (profileId: string) => {
    if (!user) return;

    try {
      const { error } = await supabase
        .from('ai_profiles')
        .delete()
        .eq('id', profileId)
        .eq('parent_id', user.id);

      if (error) throw error;

      setProfiles(prev => prev.filter(profile => profile.id !== profileId));
      
      toast({
        title: "Success!",
        description: "AI profile deleted successfully"
      });
    } catch (error) {
      console.error('Failed to delete AI profile:', error);
      toast({
        title: "Error",
        description: "Failed to delete AI profile",
        variant: "destructive"
      });
    }
  };

  const downloadProfileAsPDF = (profile: AIProfile, resumeFileName?: string) => {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>AI Generated Profile</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              margin: 40px; 
              line-height: 1.6; 
              color: #333;
            }
            .header { 
              text-align: center; 
              border-bottom: 2px solid #333; 
              padding-bottom: 20px; 
              margin-bottom: 30px; 
            }
            .content { 
              white-space: pre-wrap;
              margin-bottom: 25px; 
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #ddd;
              color: #666;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>AI Generated Profile</h1>
            ${resumeFileName ? `<p>Based on: ${resumeFileName}</p>` : ''}
            <p>Generated on: ${new Date(profile.created_at).toLocaleDateString()}</p>
          </div>
          
          <div class="content">
            ${profile.summary}
          </div>
          
          <div class="footer">
            <p>Generated by ShadchanApp AI Profile Generator</p>
          </div>
        </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AI_Profile_${Date.now()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return {
    profiles,
    isLoading,
    isGenerating,
    generateAIProfile,
    loadAIProfiles,
    deleteAIProfile,
    downloadProfileAsPDF
  };
};
